FROM python:3.12-slim-bookworm

RUN mkdir -p /app
WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y git && \
    git clone https://github.com/mongodb-labs/py-tpcc.git /app/py-tpcc && \
    apt-get remove -y git && apt-get autoremove -y

RUN pip install --upgrade pip
RUN pip install psycopg2-binary cassandra-driver pycassa

WORKDIR /app/py-tpcc
