#cloud-config
package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - software-properties-common
  - wget
  - gnupg2
  - openjdk-11-jdk
  - python2

write_files:
  # Auto-restart cassandra
  - path: /etc/systemd/system/cassandra.service.d/override.conf
    owner: root:root
    permissions: "0644"
    content: |
      [Service]
      Restart=on-failure
      RestartSec=5
  # Node Exporter Service
  - path: /etc/systemd/system/node_exporter.service
    owner: root:root
    permissions: "0644"
    content: |
      [Unit]
      Description=Prometheus Node Exporter
      After=network.target
      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter
      [Install]
      WantedBy=multi-user.target
  # Cassandra Exporter Service (runs a .jar with Java)
  - path: /etc/systemd/system/cassandra_exporter.service
    owner: root:root
    permissions: "0644"
    content: |
      [Unit]
      Description=Cassandra Exporter for Prometheus
      After=network.target cassandra.service
      [Service]
      User=cassandra_exporter
      Group=cassandra_exporter
      Type=simple
      ExecStart=/usr/bin/java -jar /usr/local/lib/cassandra_exporter/cassandra_exporter.jar /etc/cassandra_exporter/config.yml
      Restart=on-failure
      [Install]
      WantedBy=multi-user.target
  # Cassandra Exporter Config
  - path: /etc/cassandra_exporter/config.yml
    owner: root:root
    permissions: "0644"
    content: |
      listenAddress: 0.0.0.0
      listenPort: 7070
      user: ""
      password: ""
      host: localhost:7199
      ssl: false

      blacklist:
        # Unaccessible metrics (not enough privilege)
        - java:lang:memorypool:.*usagethreshold.*

        # Leaf attributes not interesting for us but that are presents in many path (reduce cardinality of metrics)
        - .*:999thpercentile
        - .*:95thpercentile
        - .*:fifteenminuterate
        - .*:fiveminuterate
        - .*:durationunit
        - .*:rateunit
        - .*:stddev
        - .*:meanrate
        - .*:mean
        - .*:min

        # Path present in many metrics but uninterresting
        - .*:viewlockacquiretime:.*
        - .*:viewreadtime:.*
        - .*:cas[a-z]+latency:.*
        - .*:colupdatetimedeltahistogram:.*

        # Mostly for RPC, do not scrap them
        - org:apache:cassandra:db:.*

        # columnfamily is an alias for Table metrics in cassandra 3.x
        # https://github.com/apache/cassandra/blob/8b3a60b9a7dbefeecc06bace617279612ec7092d/src/java/org/apache/cassandra/metrics/TableMetrics.java#L162
        - org:apache:cassandra:metrics:columnfamily:.*

        # Should we export metrics for system keyspaces/tables ?
        - org:apache:cassandra:metrics:[^:]+:system[^:]*:.*

        # Don't scrape us
        - com:criteo:nosql:cassandra:exporter:.*

      maxScrapFrequencyInSec:
        50:
          - .*

        # Refresh those metrics only every hour as it is costly for cassandra to retrieve them
        3600:
          - .*:snapshotssize:.*
          - .*:estimated.*
          - .*:totaldiskspaceused:.*

  - path: /etc/sysctl.d/99-optim.conf
    content: |
      # Increase maximum TCP buffer sizes
      net.core.rmem_max = 134217728
      net.core.wmem_max = 134217728
      net.ipv4.tcp_rmem = 4096 87380 134217728
      net.ipv4.tcp_wmem = 4096 65536 134217728

      # Enable TCP window scaling
      net.ipv4.tcp_window_scaling = 1

      # Reduce TCP connection latency
      net.ipv4.tcp_timestamps = 0
      net.ipv4.tcp_sack = 1
      net.ipv4.tcp_no_metrics_save = 1
      net.ipv4.tcp_mtu_probing = 1

      # Increase max socket backlog
      net.core.somaxconn = 4096

      # Allow more open files and connections
      fs.file-max = 2097152

      # Enable memory overcommit
      vm.overcommit_memory = 2
      vm.overcommit_ratio = 95

      # Enable huge pages support
      vm.nr_hugepages = 128

      # Reduce swappiness
      vm.swappiness = 1

runcmd:
  # Wait for networking
  - |
    until ip route get 172.16.12.0 &> /dev/null; do
      echo "Waiting for network route..."
      sleep 2
    done

  # Random startup delay (20–50 seconds)
  - |
    delay=$((RANDOM % 30 + 20))
    echo "Sleeping $delay seconds to reduce boot storm..."
    sleep $delay

  # Apply sysctl
  - sysctl --system

  # Increase resource limits
  - echo "* soft nofile 1048576" | tee -a /etc/security/limits.conf
  - echo "* hard nofile 1048576" | tee -a /etc/security/limits.conf
  - echo "* soft memlock unlimited" | tee -a /etc/security/limits.conf
  - echo "* hard memlock unlimited" | tee -a /etc/security/limits.conf

  # DO Monitoring Agent
  - curl -sSL https://repos.insights.digitalocean.com/install.sh | sudo bash

  # Install Cassandra
  - curl -o /etc/apt/keyrings/apache-cassandra.asc https://downloads.apache.org/cassandra/KEYS
  - echo "deb [signed-by=/etc/apt/keyrings/apache-cassandra.asc] https://debian.cassandra.apache.org 41x main" | tee /etc/apt/sources.list.d/cassandra.sources.list
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -yq cassandra
  - systemctl disable cassandra # Prevent early boot

  # Configure Cassandra
  - |
    ip=$(ip route get 172.16.12.0 | awk '{print $(NF-2); exit}')
    sed -i "s/^listen_address: localhost/listen_address: ${ip}/" /etc/cassandra/cassandra.yaml
    sed -i "s/^rpc_address: localhost/rpc_address: 0.0.0.0/" /etc/cassandra/cassandra.yaml
    sed -i "s/^endpoint_snitch: SimpleSnitch/endpoint_snitch: GossipingPropertyFileSnitch/" /etc/cassandra/cassandra.yaml
    sed -i "s/^# broadcast_address:.*/broadcast_address: ${ip}/" /etc/cassandra/cassandra.yaml
    sed -i "s/^# broadcast_rpc_address:.*/broadcast_rpc_address: ${ip}/" /etc/cassandra/cassandra.yaml
    sed -i 's/seeds: .*/seeds: "cassandra-01.private.do-usp.lelis.gay"/' /etc/cassandra/cassandra.yaml

  # Wait for seed unless we're the seed
  - |
    if ! hostname | grep -q cassandra-01; then
      echo "Waiting for seed node cassandra-01 to become reachable..."
      while ! nc -z cassandra-01.private.do-usp.lelis.gay 7000; do
        echo "Seed not reachable yet on port 7000..."
        sleep 5
      done
    else
      echo "This is the seed node, skipping wait."
    fi

  # Start Cassandra safely
  - systemctl daemon-reload
  - systemctl enable cassandra
  - |
    echo "Starting Cassandra..."
    systemctl start cassandra || {
      echo "Cassandra start failed, retrying in 10s..."
      sleep 10
      systemctl restart cassandra
    }

  # Node exporter
  - wget https://github.com/prometheus/node_exporter/releases/download/v1.9.1/node_exporter-1.9.1.linux-amd64.tar.gz
  - tar xvfz node_exporter-*.linux-amd64.tar.gz
  - mv node_exporter-*/node_exporter /usr/local/bin/
  - useradd --no-create-home --shell /bin/false node_exporter
  - chown node_exporter:node_exporter /usr/local/bin/node_exporter
  - systemctl daemon-reload
  - systemctl enable --now node_exporter

  # Cassandra exporter
  - useradd --no-create-home --shell /bin/false cassandra_exporter
  - mkdir -p /usr/local/lib/cassandra_exporter
  - wget -O /usr/local/lib/cassandra_exporter/cassandra_exporter.jar https://github.com/criteo/cassandra_exporter/releases/download/2.3.8/cassandra_exporter-2.3.8.jar
  - chown -R cassandra_exporter:cassandra_exporter /usr/local/lib/cassandra_exporter
  - mkdir -p /etc/cassandra_exporter
  - chown -R cassandra_exporter:cassandra_exporter /etc/cassandra_exporter
  - systemctl daemon-reload
  - systemctl enable --now cassandra_exporter
