#cloud-config
package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - software-properties-common
  - wget
  - gnupg2
  - openjdk-11-jdk
  - python2

write_files:
  # Auto-restart cassandra
  - path: /etc/systemd/system/cassandra.service.d/override.conf
    owner: root:root
    permissions: "0644"
    content: |
      [Service]
      Restart=on-failure
      RestartSec=5
  # Node Exporter Service
  - path: /etc/systemd/system/node_exporter.service
    owner: root:root
    permissions: "0644"
    content: |
      [Unit]
      Description=Prometheus Node Exporter
      After=network.target
      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter
      [Install]
      WantedBy=multi-user.target
  # Cassandra Exporter Service (runs a .jar with Java)
  - path: /etc/systemd/system/cassandra_exporter.service
    owner: root:root
    permissions: "0644"
    content: |
      [Unit]
      Description=Cassandra Exporter for Prometheus
      After=network.target cassandra.service
      [Service]
      User=cassandra_exporter
      Group=cassandra_exporter
      Type=simple
      ExecStart=/usr/bin/java -jar /usr/local/lib/cassandra_exporter/cassandra_exporter.jar /etc/cassandra_exporter/config.yml
      Restart=on-failure
      [Install]
      WantedBy=multi-user.target
  # Cassandra Exporter Config
  - path: /etc/cassandra_exporter/config.yml
    owner: root:root
    permissions: "0644"
    content: |
      listenAddress: 0.0.0.0
      listenPort: 7070
      user: ""
      password: ""
      host: localhost:7199
      ssl: false

      blacklist:
        # Unaccessible metrics (not enough privilege)
        - java:lang:memorypool:.*usagethreshold.*

        # Leaf attributes not interesting for us but that are presents in many path (reduce cardinality of metrics)
        - .*:999thpercentile
        - .*:95thpercentile
        - .*:fifteenminuterate
        - .*:fiveminuterate
        - .*:durationunit
        - .*:rateunit
        - .*:stddev
        - .*:meanrate
        - .*:mean
        - .*:min

        # Path present in many metrics but uninterresting
        - .*:viewlockacquiretime:.*
        - .*:viewreadtime:.*
        - .*:cas[a-z]+latency:.*
        - .*:colupdatetimedeltahistogram:.*

        # Mostly for RPC, do not scrap them
        - org:apache:cassandra:db:.*

        # columnfamily is an alias for Table metrics in cassandra 3.x
        # https://github.com/apache/cassandra/blob/8b3a60b9a7dbefeecc06bace617279612ec7092d/src/java/org/apache/cassandra/metrics/TableMetrics.java#L162
        - org:apache:cassandra:metrics:columnfamily:.*

        # Should we export metrics for system keyspaces/tables ?
        - org:apache:cassandra:metrics:[^:]+:system[^:]*:.*

        # Don't scrape us
        - com:criteo:nosql:cassandra:exporter:.*

      maxScrapFrequencyInSec:
        50:
          - .*

        # Refresh those metrics only every hour as it is costly for cassandra to retrieve them
        3600:
          - .*:snapshotssize:.*
          - .*:estimated.*
          - .*:totaldiskspaceused:.*

runcmd:
  - curl -sSL https://repos.insights.digitalocean.com/install.sh | sudo bash

  # Add Cassandra repository and install Cassandra
  - curl -o /etc/apt/keyrings/apache-cassandra.asc https://downloads.apache.org/cassandra/KEYS
  - echo "deb [signed-by=/etc/apt/keyrings/apache-cassandra.asc] https://debian.cassandra.apache.org 41x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -yq cassandra

  # Configure Cassandra to listen on the private IP (adjust if you want to use hostname here instead)
  - |
    sed -i "s/^listen_address: localhost/listen_address: $(ip route get 172.16.12.0 | awk '{print $(NF-2); exit}')/" /etc/cassandra/cassandra.yaml
  - |
    sed -i "s/^rpc_address: localhost/rpc_address: 0.0.0.0/" /etc/cassandra/cassandra.yaml
  - |
    sed -i "s/^endpoint_snitch: SimpleSnitch/endpoint_snitch: GossipingPropertyFileSnitch/" /etc/cassandra/cassandra.yaml
  - |
    sed -i "s/^# broadcast_address:.*/broadcast_address: $(ip route get 172.16.12.0 | awk '{print $(NF-2); exit}')/" /etc/cassandra/cassandra.yaml
  - |
    sed -i "s/^# broadcast_rpc_address:.*/broadcast_rpc_address: $(ip route get 172.16.12.0 | awk '{print $(NF-2); exit}')/" /etc/cassandra/cassandra.yaml

  # # Set the seeds to all three DNS records
  # - |
  #   sed -i "s/^seeds: .*/seeds: \"cassandra-01.private.do-usp.lelis.gay,cassandra-02.private.do-usp.lelis.gay,cassandra-03.private.do-usp.lelis.gay\"/" /etc/cassandra/cassandra.yaml
  # Set the seeds to only the first node
  - |
    sed -i 's/seeds: .*/seeds: "cassandra-01.private.do-usp.lelis.gay"/' /etc/cassandra/cassandra.yaml

  # Start Cassandra
  - systemctl daemon-reload
  - systemctl enable --now cassandra

  # Install and run node_exporter
  - wget https://github.com/prometheus/node_exporter/releases/download/v1.9.1/node_exporter-1.9.1.linux-amd64.tar.gz
  - tar xvfz node_exporter-*.linux-amd64.tar.gz
  - mv node_exporter-*/node_exporter /usr/local/bin/
  - useradd --no-create-home --shell /bin/false node_exporter
  - chown node_exporter:node_exporter /usr/local/bin/node_exporter
  - systemctl daemon-reload
  - systemctl enable --now node_exporter

  # Install and run cassandra_exporter (as a Java .jar)
  - useradd --no-create-home --shell /bin/false cassandra_exporter
  - mkdir -p /usr/local/lib/cassandra_exporter
  - wget -O /usr/local/lib/cassandra_exporter/cassandra_exporter.jar https://github.com/criteo/cassandra_exporter/releases/download/2.3.8/cassandra_exporter-2.3.8.jar
  - chown -R cassandra_exporter:cassandra_exporter /usr/local/lib/cassandra_exporter
  - mkdir -p /etc/cassandra_exporter
  - chown -R cassandra_exporter:cassandra_exporter /etc/cassandra_exporter
  - systemctl daemon-reload
  - systemctl enable --now cassandra_exporter
