#cloud-config
package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - software-properties-common
  - wget
  - gnupg2
  - prometheus
  - jq

write_files:
  # Prometheus data source for Grafana
  - path: /etc/grafana/provisioning/datasources/prometheus.yaml
    owner: root:root
    permissions: "0644"
    content: |
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://localhost:9090
        isDefault: true

  # Dashboard provider definition
  - path: /etc/grafana/provisioning/dashboards/default.yaml
    owner: root:root
    permissions: "0644"
    content: |
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards

  # Prometheus configuration file
  - path: /etc/prometheus/prometheus.yml
    owner: root:root
    permissions: "0644"
    content: |
      global:
        scrape_interval: 15s
        evaluation_interval: 15s

      scrape_configs:
        # Scrape node_exporter metrics from all Citus and Cassandra nodes
        - job_name: 'node'
          static_configs:
            - targets:
              - 'postgres-01.private.do-usp.lelis.gay:9100'
              - 'postgres-02.private.do-usp.lelis.gay:9100'
              - 'postgres-03.private.do-usp.lelis.gay:9100'
              - 'cassandra-01.private.do-usp.lelis.gay:9100'
              - 'cassandra-02.private.do-usp.lelis.gay:9100'
              - 'cassandra-03.private.do-usp.lelis.gay:9100'

        # Scrape postgres_exporter metrics from all Citus nodes
        - job_name: 'postgres'
          static_configs:
            - targets:
              - 'postgres-01.private.do-usp.lelis.gay:9187'
              - 'postgres-02.private.do-usp.lelis.gay:9187'
              - 'postgres-03.private.do-usp.lelis.gay:9187'

        # Scrape cassandra_exporter metrics from all Cassandra nodes
        - job_name: 'cassandra'
          static_configs:
            - targets:
              - 'cassandra-01.private.do-usp.lelis.gay:7070'
              - 'cassandra-02.private.do-usp.lelis.gay:7070'
              - 'cassandra-03.private.do-usp.lelis.gay:7070'

runcmd:
  # Add Grafana GPG key and install Grafana
  - mkdir -p /etc/apt/keyrings
  - wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/grafana.gpg > /dev/null
  - echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
  - apt-get update -y
  - DEBIAN_FRONTEND=noninteractive apt-get install -yq grafana

  # Create dashboard directory
  - mkdir -p /var/lib/grafana/dashboards

  # Download and install node_exporter dashboard (ID 1860)
  - wget -O /var/lib/grafana/dashboards/node_exporter.json https://grafana.com/api/dashboards/1860/revisions/latest/download

  # Download and install postgres_exporter dashboard (ID 12485)
  - wget -O /var/lib/grafana/dashboards/postgres_exporter.json https://grafana.com/api/dashboards/12485/revisions/latest/download

  # Download and install cassandra_exporter dashboard
  - wget -O /var/lib/grafana/dashboards/cassandra_exporter.json https://github.com/criteo/cassandra_exporter/raw/refs/heads/master/grafana/cassandra_default.json

  # Update prometheus ownership
  - chown -R prometheus:prometheus /etc/prometheus

  # Start and enable Prometheus
  - systemctl enable --now prometheus
  - sytemctl restart prometheus

  # Start and enable Grafana
  - systemctl enable --now grafana-server
