global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres_exporter:9187"]
