FROM postgres:17.2

RUN apt-get update\
    && apt-get install -y --no-install-recommends \
       iproute2\
       ca-certificates\
    && rm -rf /var/lib/apt/lists/*

COPY pg_healthcheck /
COPY 002-increase-max-conn.sql /docker-entrypoint-initdb.d/

HEALTHCHECK --interval=4s --start-period=6s CMD ./pg_healthcheck
